version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: iic_backend
    restart: always
    environment:
      - DATABASE_URL=file:/data/dev.db
      - JWT_SECRET=production_secret_key_change_me
    volumes:
      - sqlite_data:/data
      - uploads_data:/app/public/uploads

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: iic_frontend
    restart: always
    ports:
      - "6901:80"
    depends_on:
      - backend

volumes:
  sqlite_data:
  uploads_data:
